language: node_js # 指定环境为 Node.js

node_js:
  - lts/*

before_install:
  - export TZ='Asia/Hangzhou' # 设置时区 非必须

script:
  - npm run docs:build # 执行命令

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist # 部署的文件夹文件
  github_token: access_token # travis服务上的token变量
  keep_history: true
  on:
    branch: master

notifications:
  email: false
